### ISSUE TITLE
Question: Background Workers / Long Running Processes

### ISSUE THREAD

**Issue by Glathrop** [senecajs/seneca-amqp-transport#128]
Relative noob here with a definite noob problem...

**SETUP**
Running Seneca & seneca-amqp with RabbitMQ & Node.

**PROBLEM**
Cannot figure out how to get a message into a rabbitmq queue that exists & processes independently of the Seneca timeout. The "job" is to update a document. Updating the document uses a seneca action and therefore is subjected to timeout. It seems to be a catch 22. 

**SPECIFICS**
In a CRM, a cron runs and gets all active "prospects" documents. I loop over and increment a counter on a "days_since_inbound_communication" field. The loop fires off a Seneca command to update each prospect. Loop currently times out. 

I'm struggling with forming a mental model on how to approach this. What I need is for the cron to get all documents and notify a worker that a job needs to be started. Seneca response to cron from worker should essentially say "I've started the job" and cron response is resolved. Background worker then starts processing jobs.

Is seneca-amqp setup to handle workers or am I using the wrong tool for the job? Should I just use something like amqplib to set this up? Does anyone have an example of using seneca-amqp for both commands and workers?

Apologies for not asking with clarity. As I'm not sure how to think about this, I'm struggling to frame this problem in a way that makes sense.

**Comment by me23** [comment]
Why do you not response early to the seneca command and then process the long running task? Then the caller have not to wait for finishing the task. If you need to be informed as soon as the long running task is finish, send a "command finish" message which the caller is listening on

**Comment by Glathrop** [comment]
@me23 Thanks for the reply.  This ended up being a combination of things.

One issue, [referenced here ](https://github.com/senecajs/seneca-amqp-transport/issues/63), is that Seneca AMQP apparently defaults to 25 msgs per second unless you specify the AMQP noDelay option to true. Once we changed that we saw a bump from 25 messages per second to 1k+ per second.

In the end, the issue was not really understanding some RabbitMQ fundamentals & we implemented an approach much like you were describing. When the cron has gathered all prospects we simply loop over and fire of a process_this_group type Seneca command. That function responds immediately, opens up a new channel/queue in rabbitmq and fires off RabbitMQ messages(not Seneca commands) to a queue. The worker on that queue can then process each of the messages individually in the background, using our regular Seneca style commands. This way each job has it one timeout rather than a timeout for ALL jobs. 

Things that helped:
- Fixing the noDelay issue
- Figuring out you can open and close RabbitMQ channels & queues at will as long as the CONNECTION to RabbitMQ has been opened once.
- Sorting the right place to change from a Seneca style key, value command to a RabbitMQ message.
