### ISSUE TITLE
Becoming the official plugin

### ISSUE THREAD

**Issue by nfantone** [senecajs/seneca-amqp-transport#6]
@disintegrator Some good news: we have been discussing with @geek and @mcdonnelldean (part of the Seneca core team) about [making this plugin the official AMQP transport](https://github.com/senecajs/seneca-rabbitmq-transport) in detriment of [seneca-rabbitmq-transport](https://github.com/senecajs/seneca-rabbitmq-transport).

Are you willing to participate in this? We need to make a new release with the latest changes and plan some other things for the future.

**Comment by disintegrator** [comment]
Sounds good to me. Do you (or them) think there's anything more to do before we can take over? Are we missing some key features?

**Comment by nfantone** [comment]
@disintegrator I've [asked them the same thing](https://github.com/senecajs/seneca-rabbitmq-transport/issues/20#issuecomment-173408332) but didn't receive any feedback yet.

**Comment by disintegrator** [comment]
Brilliant I'll keep an eye on the thread. Meanwhile I'll jump in and help improve the library. We sorely need more docs and tests for the library to be taken seriously.

**Comment by nfantone** [comment]
Tests would be swell. It'd also be great if no RabbitMQ instance were needed for unit testing. I've seen some [setup over at seneca-rabbitmq-transport](https://github.com/senecajs/seneca-rabbitmq-transport/blob/master/setup.sh) that fires a `rabbitmq` docker before starting. I think that kind of functional/black box testing should be written separately. What are your thoughts?

Docs have improved quite a bit. Take a look at latest `develop`.

**Comment by nfantone** [comment]
@disintegrator When you have a moment, could you please release 0.2.0 to npm? Thank you.

**Comment by disintegrator** [comment]
@nfantone done!

**Comment by nfantone** [comment]
@disintegrator Thanks!

**Comment by disintegrator** [comment]
Oh damn. Sorry I did it a rush so I didn't block you. Will follow guidelines next time

**Comment by n321203** [comment]
Just wanted to say im really happy there is an actively developed amqp-plugin. 👍

**Comment by nfantone** [comment]
@n321203 Hey, thanks, man! I hope you find the plugin useful. And, of course, feel free to contribute back. Any help is appreciated.

**Comment by nfantone** [comment]
@disintegrator Would you please consider giving me npm publishing right?  I've released and tagged `0.2.1` and I'd like to upload that.

**Comment by disintegrator** [comment]
Yep I'll look into it

**Comment by nfantone** [comment]
@disintegrator https://docs.npmjs.com/cli/owner

**Comment by luhtonen** [comment]
Any news on the discussion with seneca owners to make this official? Are there concrete plans and dates setup/agreed?

**Comment by nfantone** [comment]
@luhtonen That's a good question. Doors have been opened for quite a while now. I'm all for it. Not much to do from my end, TBH. I'm waiting for the guys at Seneca to give me the heads up. AFAIK, they have been working hard to accommodate things and put together a more cohesive plugin ecosystem, lately.

**Comment by nfantone** [comment]
@mcdonnelldean So... any changes so far? Are you guys ready for this? 🎈

**Comment by mcdonnelldean** [comment]
@nfantone Yes, sorry, as usual we are bogged down. I spoke to Richard and others about green lighting. Rather than wait for the official procession lets just get it done :D

Can you add me repo so I can move it into senecajs/ org? You will need to republish after to fix npm links. Note it will go into the same org as seneca proper, not the labs or community org.

The only rules really are to try keep a cohesive linting and tooling standard and to keep the project MIT. Usual stuff.

**Comment by nfantone** [comment]
Yey 🎂 ! Finally.

Well, repo already uses [Seneca's eslint rules](https://github.com/senecajs/eslint-config-seneca), is MIT licensed and follows [your contributing guides](http://senecajs.org/contribute/).

If you need any further changes, let me know.

**Comment by nfantone** [comment]
@mcdonnelldean Invite already sent. Check your inbox.

**Comment by mcdonnelldean** [comment]
Yup got it. Should be moved in the next couple of hours

**Comment by nfantone** [comment]
@mcdonnelldean I don't know if you have already established some guidelines for these migrations, but one approach we have been following with Koa modules is to drop the `koa-` prefix on repos names once moved onto the organization. If it's in our repo, that becomes tacit. So, for Seneca, that would make:

`https://github.com/seneca-contrib/seneca-amqp-transport` -> `https://github.com/senecajs/amqp-transport`

**Comment by mcdonnelldean** [comment]
Generally we leave it as is, we find the seneca-x way makes it easier to find things on github and npm. Should be moved in two mins.

**Comment by mcdonnelldean** [comment]
@nfantone Looks like I need to be bumped to owner to move it across. Once done ping and I'll move. (write privilege is not enough)

**Comment by nfantone** [comment]
I believe I made you _Admin_ of the repo. Let me check.

**Comment by nfantone** [comment]
@mcdonnelldean Yup. Your rank is as high as they come.

<img width="779" alt="screen shot 2016-10-11 at 7 45 22 pm" src="https://cloud.githubusercontent.com/assets/476069/19283815/4c42ec3a-8feb-11e6-9532-308db2537e1f.png">

**Comment by mcdonnelldean** [comment]
Testing, testing... Are we live, has everyone got the right access?

**Comment by nfantone** [comment]
@mcdonnelldean Seems like it.

👀 Everyone all right?

**Comment by nfantone** [comment]
@mcdonnelldean Tried pulling and pushing. Works wonders.

One thing though: do we have a team that maybe I can become a member of? This is just to show a "badge" on issues to tell people I'm maintaining the project. It used to be "seneca-contrib member" previously.

**Comment by mcdonnelldean** [comment]
Yup, I'm setting it all up now, you will end up on two or three but it always shows you are a member then.

**Comment by mcdonnelldean** [comment]
Ok I've sent the contributors one only so it doesn't go all funny from multiple requests. You should see the info here https://github.com/orgs/senecajs/teams/contributors.

**Comment by nfantone** [comment]
`404` on that URL. I suppose I don't have access to that yet.

**Comment by mcdonnelldean** [comment]
Really? Can you hit the teams page and then contributors? Your invite pops
up there too

**Comment by mcdonnelldean** [comment]
Maybe try just https://github.com/senecajs It should pop up there.

**Comment by nfantone** [comment]
There. Invitation arrived. All set, then.

Thank you very much for letting me on board! 

I'll be closing the issue.

**Comment by mcdonnelldean** [comment]
Yay!  Cc @rjrodger @paolochiodi
