### ISSUE TITLE
Every queue has a consume rate of at best 25 messages per second. How can I increase this?

### ISSUE THREAD

**Issue by ppinel** [senecajs/seneca-amqp-transport#63]
Hello,

I am using SenecaJS with this plugin and RabbitMQ. When I did some benchmarking to understand why at best I had 25 messages per second handled on each queue, I found out that it takes 40ms for a message to go and come back.
For exemple, a microservice ask for an object to another microservice (Basically a mongodb query).
The act callback is called 40ms after when Mongodb query only takes 2ms to complete.
So I now understand why on RabbitMQ admin interface, I have at best 25 messages handled per second per queue: 40ms * 25 = 1 second.

I use the default config for Amqp plugin and SenecaJS. All microservices and RabbiMQ are on the same server.
Each microservice has only one instance running.

Is this a normal behaviour? 
Is it possible to only increase the rate by modifying the parameters of Seneca AMQP Transport, SenacaJS and/or RabbitMQ ?

**Comment by nfantone** [comment]
Hi, @ppinel. Thanks for taking the time to write about your issue.

I've tested this on my side and found wildly different numbers than the ones you brought up. For instance, running the microservices on the `/examples`, both `client.js` and `listener.js` locally (and RabbitMQ `3.6.4` on `localhost`), I could get up to 820+ msg/s.

See screenshot below:

<img width="707" alt="screen shot 2016-10-17 at 5 03 41 pm" src="https://cloud.githubusercontent.com/assets/476069/19445427/1dc36b5a-948c-11e6-8f7f-df452b8f4122.png">

And while this isn't a thorough benchmark by any means, our results are _so_ different, that I'm inclined to say there's something in your topology or `.act` function that's putting a lid on the throughput.

Are you connecting to the broker locally (ie.: using `localhost`)? Was the broker under heavy load when you measured your numbers? How many queues are declared on your vhost? How many messages are on those queues, on average? Is your callback doing anything else that could amount to a significant delay? How are you measuring the RTT?

Finally, could you run the examples and share your results? Or maybe (if this isn't too much to ask), could you profile your script and tell me exactly where exec time is spent? That would be very helpful.

Thanks again!

**Comment by ppinel** [comment]
Thanks for your response. 

Yes I am connecting to the broker locally, not using any load balancer or proxy. The broker wasn't under heavy load because it's on my dev env and nobody is using it but me. 
There is 121 queues declared with 104 corresponding to response and 17 to action.
There is a low traffic on the queue in general. Microservices are behind an API gateway and can talk with each other through SenecaJS.

To understand why my action was taking too long I just set a var with the current time at the beginning of the action and displayed at different moment of the logic the diff between now and my var.
For exemple at some point of the logic MicroserviceA act on MicroserviceB. I display the time diff at right before calling the act and another display in the callback of the act.
I also do the same system on MicroserviceB to get how many ms the logic takes to execute.
I end up with 2ms on MicroserviceB and 40ms on MicroserviceA. So from here I was wondering who was taking 38ms. When I tested the charge, I end up with a max of 25 messages per second.

I am not saying is SenecaJS, RabbitMQ or anyone fault. I just want to understand why I have this results to improve where it needs to be. 
So your quick answer is much appreciated.

I will do the test asap and get back to you with results.

**Comment by nfantone** [comment]
Awesome. Your setup LGTM. Could you also include the output of RabbitMQ's web admin? In particular, I'm interested in the Acknowldeg rate.

**Comment by ppinel** [comment]
Here the exemple running on my server. I am lost oO

<img width="865" alt="screen shot 2016-10-18 at 16 14 02" src="https://cloud.githubusercontent.com/assets/2622533/19481430/33312e1a-954e-11e6-87cc-dba50afb3d42.png">

<img width="1620" alt="screen shot 2016-10-18 at 16 13 51" src="https://cloud.githubusercontent.com/assets/2622533/19481429/33186ccc-954e-11e6-8622-c5444b53330f.png">

**Comment by ppinel** [comment]
On my macbook pro:
<img width="1671" alt="screen shot 2016-10-18 at 16 40 03" src="https://cloud.githubusercontent.com/assets/2622533/19482517/9e9a63bc-9551-11e6-8304-071c57e3155f.png">
<img width="1680" alt="screen shot 2016-10-18 at 16 39 24" src="https://cloud.githubusercontent.com/assets/2622533/19482518/9ea93586-9551-11e6-9074-e69a33f7b889.png">

**Comment by ppinel** [comment]
I just reinstall RabbitMQ on the server and still have the same issue.

**Comment by nfantone** [comment]
@ppinel All right. Numbers on your Macbook look a lot more than what I'd expect. What other differences can you think of between your local env and your server? 

Consider:

- [ ] `seneca`, `seneca-amqp-transport` versions.
- [x] Node version (`6.8.1` in both).
- [ ] RabbitMQ version (I can see it's `3.6.1` on you laptop).
- [ ] Is your server running inside a VM or a container?

Also, you did change `setInterval` argumento to `0` in both cases, right?

**Comment by ppinel** [comment]
Yes I did changed setInterval in both cases, otherwise messages are coming to slowly and I never reach the mysterious limit.
3.6.1 on my server too, and seneca, seneca-amqp-transport versions are the same.

Regarding the server it's from a french hosting service OVH.
https://www.soyoustart.com/fr/offres/e3-ssd-2.xml or
https://www.soyoustart.com/fr/offres/e3-ssd-3.xml
So dedicated server.

**Comment by ppinel** [comment]
It could be on the OS layer. Is there any limitation you had to change or met someone with issues on Debian?
I am looking at the Overview tab and nothing have crazy value as fd, socket, memory etc.

**Comment by nfantone** [comment]
I'm perplexed. And out of ideas.

Could you please read and check [this](https://www.rabbitmq.com/flow-control.html) out? Use the `rabbitmqctl` in your server to check  if the connection is being stalled.

**Comment by nfantone** [comment]
> It could be on the OS layer. Is there any limitation you had to change or met someone with issues on Debian?

Although rare, it _could_ be. Check the **Process statistics** panel on _Overview -> (More about this node)_ and take a look at the thresholds in each graph. For example, mine look like this:

<img width="886" alt="screen shot 2016-10-18 at 5 23 02 pm" src="https://cloud.githubusercontent.com/assets/476069/19486818/c8ef1be8-9557-11e6-84ce-5aff1b68a635.png">

Also, is your RabbitMQ node Disc or RAM based?

**Comment by ppinel** [comment]
First one is while running exemple, second one is before.

I can't tell if my RabbitMQ is disk or memory based. How can I know this?

<img width="989" alt="screen shot 2016-10-18 at 18 40 01" src="https://cloud.githubusercontent.com/assets/2622533/19487270/5702f2ec-9562-11e6-8e46-14d7a9279f3e.png">
<img width="864" alt="screen shot 2016-10-18 at 18 39 03" src="https://cloud.githubusercontent.com/assets/2622533/19487271/570703aa-9562-11e6-954f-bf29c8f56682.png">

**Comment by nfantone** [comment]
Ok, so no problems there.

> I can't tell if my RabbitMQ is disk or memory based. How can I know this?

There' a tag under the node's title on its description page. It also appears on the Overview tab.

<img width="428" alt="screen shot 2016-10-18 at 5 49 35 pm" src="https://cloud.githubusercontent.com/assets/476069/19487553/476e9e28-955b-11e6-9d04-48ce2d20e133.png">

Did you manage to check the `flow` status of your connection?

**Comment by ppinel** [comment]
Ok disk everywhere.
Also tested on a fresh AWS EC2 on debian and same issue.

<img width="977" alt="screen shot 2016-10-18 at 18 52 05" src="https://cloud.githubusercontent.com/assets/2622533/19487683/20279136-9564-11e6-8476-70c922bcd564.png">

**Comment by ppinel** [comment]
What's 48MB low watermark ? 
<img width="879" alt="screen shot 2016-10-18 at 18 54 54" src="https://cloud.githubusercontent.com/assets/2622533/19487762/6618e118-9564-11e6-9c39-1483dece1f85.png">

**Comment by ppinel** [comment]
I checked on the connections tab during a test:
<img width="716" alt="screen shot 2016-10-18 at 18 58 22" src="https://cloud.githubusercontent.com/assets/2622533/19487900/f42c1a7e-9564-11e6-9b27-a59ca022d6da.png">

**Comment by nfantone** [comment]
> What's 48MB low watermark ? 
Minimum free space needed for the node to run.
---

Ok, so no throttling on the connection. This looks like a non-arbitrary fixed cap of sorts. 25 is too much of a nice round number to be a coincidence.

**Comment by ppinel** [comment]
Also it's the same number across server even on the aws ec2 instance.
I created a stackoverflow question: http://stackoverflow.com/questions/40114532/every-queue-has-a-consume-rate-of-at-best-25-messages-per-second-how-can-i-incr

**Comment by ppinel** [comment]
Thank you for your time, I'll post an update here as soon as I have the solution.

**Comment by nfantone** [comment]
Thanks! Yes, if you come up with a solution, please share it. I'm intrigued now.

**Comment by ppinel** [comment]
I  wanted to know if by any chance you take advantage of this option https://github.com/squaremo/amqp.node/blob/master/lib/connect.js#L98?
Idea from this post https://groups.google.com/forum/#!searchin/rabbitmq-discuss/performance$20problem/rabbitmq-discuss/3eiFVoQVfUU/ELOeTOU8EE8J

**Comment by ppinel** [comment]
I hardcoded the no delay option in amqplib to true and I have 930 messages deliver per second with the example.
I know why this is usefull but maybe I could decrease the delay.

<img width="1655" alt="screen shot 2016-10-19 at 09 25 39" src="https://cloud.githubusercontent.com/assets/2622533/19509407/d3c879d8-95de-11e6-8ae5-c05b1e36cfbd.png">

**Comment by ppinel** [comment]
Found out how to set the noDelay option: `{ amqp: { socketOptions: { noDelay: true } } }`.

**Comment by nfantone** [comment]
Had no idea about that `noDelay` flag. And I assume that if kept `false`, the delay in socket communication is OS dependant? That would explain your behaviour on Debian.

You learn something new everyday. Thanks for your teachings 🐐 ! Perhaps, I can include this in some **FAQ** section on the `README.md` or the wiki.

Feel free to close the issue if you think there's nothing else you can do to improve your message rate.

**Comment by ppinel** [comment]
Yes it's OS dependant. Would be great if this flag could be documented.
Also, this might not be the right solution for everyone.
Thanks again for your help!

**Comment by nfantone** [comment]
@ppinel After reading the whole thread on that Google Groups forum, I'm inclined to say that your solution with `noDelay: true` is very reasonable. And it _is_ platform dependant, as you mentioned above. [Nagle](https://en.wikipedia.org/wiki/Nagle%27s_algorithm) will throttle the communication on the TCP level to avoid congestion on the network, by "joining together" packets and avoid sending small segments.

Glad you could work things out. Good work.

**Comment by Glathrop** [comment]
> Found out how to set the noDelay option: `{ amqp: { socketOptions: { noDelay: true } } }`.

@ppinel I know this was a while ago... but where? In seneca-amqp options or hardcoded in amqplib like you referenced earlier?
