### ISSUE TITLE
Can't set durable: false or can't specify message TTL

### ISSUE THREAD

**Issue by sskim1** [senecajs/seneca-amqp-transport#65]
I'm trying to set the queue's durability to false with this: 

```js
require('seneca')()
    .use('seneca-amqp-transport', {
        amqp: {
            client: {
                queues: {
                    options: {
                        durable: false
                    }
                }
            }
        }
    });
```

However, this doesn't do anything. I am also trying to set a message-ttl. Is this even possible?

**Comment by nfantone** [comment]
Hi, @sskim1!

Which version of the plugin are you using? On latest (`2.1.0`), message TTL is [already set by default](https://github.com/senecajs/seneca-amqp-transport/blob/2.1.0/defaults.json#L54) to 10 seconds. You can change it to whatever you need.

On the other hand, your snippet is good and is working fine. The thing is, client queues a declared with `AD` (auto delete) and **`Excl`** (exclusive) flags by default - both of which already make the queue non durable. In other words, you should get a queue like this:

<img width="625" alt="screen shot 2016-10-25 at 8 35 15 pm" src="https://cloud.githubusercontent.com/assets/476069/19701307/bb92614e-9af2-11e6-984a-4a32001ad4e2.png">

So, setting `durable: false` is completely redundant.

On the other hand, if you wanted to set it to `true`, you should use:

```js
require('seneca')()
  .use('seneca-amqp-transport', {
    amqp: {
      client: {
        queues: {
          options: {
            durable: true,
            autoDelete: false,
            exclusive: false
          }
        }
      }
    }
  })
```

**Comment by sskim1** [comment]
I was on an old version. Thanks for the quick reply!!
