### ISSUE TITLE
How to limit message consumption rate for services?

### ISSUE THREAD

**Issue by ericnograles** [senecajs/seneca-amqp-transport#69]
Hi @nfantone,

I ran into a scenario that I think warranted a little discussion before I attempted to attack it.

I've "rolled my own" microservice framework with my team before using a variety of libraries + amqplib, which is why Seneca was such a revelation to me.  I certainly can appreciate the thought put into this framework and its plugins.

One situation I remember that we had to handle was limiting the consumption rate of services.  In other words, the capability to configure a service to consume only, say, 500 messages at a time.  We had to do this for several reasons:

1. We had to handle massive load, upwards of 10,000 reqs/sec at peak from user and integration traffic
1. In our microservice ecosystem, we'd sit have numerous instances of services (on Heroku) listening on a particular exchange and queue.  If no limit was set, one (or a small subset) of services would monopolize all message handling and we couldn't really achieve true load balancing.
1. As a side effect to the above, when the one (or subset) of services gets overwhelmed with requests, users experience service degradation.  The users that were lucky enough to have their messages processed by the non-pegged services would experience good throughput while the ones unfortunate enough to have their messages handled by the pegged services would see major latency
1. Avoid having services run out of memory due to processing too many messages at a time

I know that RabbitMQ has a `maxLength` property you can set on queues, but that wouldn't necessarily be the best solution.  I know, natively on AMQP, you can do something like setting basic.qos, but that's on the channel level.

My next instinct was then to bake it into the service implementation itself.  Perhaps something internally that keeps track of the number of messages a service is currently processing, but I was unclear as to how to tell the service instance to then not handle a message it received and kick it back to the queue for another service instance to handle.

Anyway, what would your suggestion be to attack this problem within the context of Seneca and the AMQP transport?

Thanks!

Eric

**Comment by nfantone** [comment]
Hi @ericnograles!

> I know that RabbitMQ has a maxLength property you can set on queues, but that wouldn't necessarily be the best solution. I know, natively on AMQP, you can do something like setting basic.qos, but that's on the channel level.

But those settings _really_ sound like what you are after. There are two ways to go about this: you either limit publishing rates or throttle consumers. 

Those flags were designed to control flow and manage scenarios like que ones you described well. Moreover, RabbitMQ has a [flow control system](https://www.rabbitmq.com/flow-control.html) baked in. You may want to play around with that, as well. There's also a [service blockage mechanism](https://www.rabbitmq.com/memory.html) based on memory consumption and disk usage.

So while you _could_ implement some sort of logic to regulate message's throughput client-side, my opinion is that it'd never be as good as what the broker already does - which is really its _job_.

> I was unclear as to how to tell the service instance to then not handle a message it received and kick it back to the queue for another service instance to handle.

Why not spawn multiple services? I know this won't manage flow control, but why make a consumer fetch a message just to "kick it back" to another one just like him? Declare more than one consumer on a given queue and let RabbitMQ round-robin between them. Although I'm sure you are already doing this and my suggestion sound silly - but it really is the way to go.

**Comment by nfantone** [comment]
By the way -and while we are still on the subject-, the way to "kick" a message back to queue is by `ch.ack(msg)` it,  setting `requeue` to `true` (see [the doc](http://www.squaremobius.net/amqp.node/channel_api.html#channel_nack)).

**Comment by ericnograles** [comment]
Great thoughts, @nfantone I'll definitely investigate at the AMQP level and report back.  That was my preferred solution as well, as it really is the concern of infrastructure vs. app.  I'll post what I end up doing as I experiment with a few things, as I'm sure that could be of help for others.

Thanks!

**Comment by nfantone** [comment]
Sure thing.

Shout if you end up wanting to implement something on the transport. The way I'm thinking about it, it shouldn't be too hard. As you said, you'd need to keep a record of how many unack'd messages a particular service is holding at any moment. If that number if higher than a certain configured threshold, just reject and requeue incoming messages (`.nack`) while the condition still holds true.

The only problem I could see with that approach is reaching a scenario where messages just keep looping in-and-out of the queue, when every consumer is at full bandwidth. But I supposed that's to be expected?

**Comment by nfantone** [comment]
@ericnograles Any luck with this?

**Comment by ericnograles** [comment]
@nfantone Sorry for the radio silence, as I've been a bit busy with a client!  I have a draft but I want to refine it some more as it feels a little hacky.  Hopefully will have a PR in place by this weekend so we can discuss.

As it so happens, our old use case where one service would "hog" all the messages wasn't really happening at load with Seneca.  I tested on a Heroku cluster and the work seemed to be divvied up properly among 3 services listening for the same Seneca command.  So, I'm not sure this would necessarily be a _critical_ thing to have, but I'll complete it anyway just in case.

**Comment by nfantone** [comment]
@ericnograles I agree: it's not a _critical_ feature. So a PR is not really needed, TBH. Feel free to close the issue if you don't have the time for this.
