### ISSUE TITLE
How can I separate client queues by environment?

### ISSUE THREAD

**Issue by ppinel** [senecajs/seneca-amqp-transport#70]
Hello,

I have different environments on a same server using the same RabbitMQ instance.
I am using prefix option to prefix queue name for each micro services.

Issue is on the client side. When I add clients to a micro service, from what I understood, the queue name is based on pins. Pins are the same on each environment, so I have conflicts. 
Response queue is the same across environment, if I am correct.

I though about adding an option in my micro service config files to also prefix pins.
What's the best practice here?

**Comment by nfantone** [comment]
Hello, @ppinel. Thanks for using the transport.

A couple of things here to say.

The way different environments are usually managed is by setting up different broker instances. I know this may sound trivial, but that's what you and your team should really be doing. Maybe take advantage of VMs, Docker, vagrant, and whatnot.

Having said that, there are some alternatives to that:

- Use **different vhosts**. Virtual hosts in RabbitMQ are a collection of queues and exchanges with restricted access per user. You can then, start the microservice for each environment with different connection URIs. Clean solution.
- Use the `amqp.queues.*.prefix` options to name your queues. You can set that to something like `seneca.listen.dev` for one environment and `seneca.listen.staging` on another, for instance.
- Use the `name` configuration attribute on `.listen()` to give a custom name to your queue.

So,

> When I add clients to a micro service, from what I understood, the queue name is based on pins. 
It is build from `pins` and prefixed by the aforementioned properties in the plugin's configuration.

> Response queue is the same across environment, if I am correct.
Not exactly. Client queues' names are randomly generated. So you won't get the same name every time you fire up your service.

> I though about adding an option in my micro service config files to also prefix pins.
It's already there 😃 .

> What's the best practice here?
Definitely, different RabbitMQ instances. Book-keeping of queues and messages is costly and the more you have on a broker, the slower it performs. If you can't do that, go with different virtual hosts per environment.

**Comment by ppinel** [comment]
Really great answer!
Thank you!

**Comment by nfantone** [comment]
You are welcome!
