### ISSUE TITLE
Multiple URLs for failover configuration

### ISSUE THREAD

**Issue by seonixx** [senecajs/seneca-amqp-transport#76]
Is there any way to set multiple URLs for use as a failover when two proxy URIs are available?

**Comment by nfantone** [comment]
@seonixx Hi, there. Thanks for writing.

No, there's no baked-in support for a failover mechanism, currently. What I'd suggest you do is handling that in the network layer by setting up some kind of load balancer, such as [HAProxy](www.haproxy.org/), that would abstract away calls to an AMQP cluster with multiple nodes.

**Comment by seonixx** [comment]
@nfantone Yeah makes sense. Thanks for your prompt reply.
