### ISSUE TITLE
Support for persistent messages

### ISSUE THREAD

**Issue by behrad** [senecajs/seneca-amqp-transport#93]
Can `persistent` option be added here https://github.com/senecajs/seneca-amqp-transport/blob/develop/lib/client/publisher.js#L31 to support for durable micro-service messaging?

That would be very nice, since I've not seen any other seneca plugin to support that. Does any?

**Comment by nfantone** [comment]
@behrad Not a bad idea at all. Many thanks for the suggestion. 

Will work on it now and keep you posted!

**Comment by nfantone** [comment]
@behrad Would you like to try the feature out before releasing?

https://github.com/senecajs/seneca-amqp-transport/pull/96

Let me know about your feedback.

**Comment by behrad** [comment]
Great to hear from you. I'll give it a try 👍 

it suddenly came to my mind, for persistent messages to work, queue should not be exclusive if I'm right.
Is queue's exclusive-ness configurable, as documentation states otherwise.

another question, have you got any number performance wise? pub/sec? consume/sec?

**Comment by nfantone** [comment]
@behrad Thank you very much, indeed.

> Is queue's exclusive-ness configurable, as documentation states otherwise.
Queues' declaration parameters are completely configurable. `"exclusive": true` is the default value, but you may change that by supplying a `client.queues.options`or `listener.queues.options` arguments via `.use()` or `.client()`/`.listen()` methods.

```json
      "queues": {
        "prefix": "seneca.act",
        "separator": ".",
        "options": {
          "autoDelete": true,
          "exclusive": true, // <-- This is what you are interested in
          "arguments": {
            "x-dead-letter-exchange": "seneca.dlx",
            "x-message-ttl": 10000
          }
        }
      }
```

> another question, have you got any number performance wise? pub/sec? consume/sec?

Those _greatly_ depend on your specs and your broker's current load/capacity. They are not hard to come by: run a few of the `/examples` and produce some numbers. They'll serve as a hint, but will be largely artificial, ind you. I know it's a no-brainer, but best way would be to run it in your production env and crunch the actual values.

**Comment by nfantone** [comment]
@behrad So, did you get a chance to try the PR? Or shall I merge regardless?

**Comment by nfantone** [comment]
Added in [v2.2.0](https://github.com/senecajs/seneca-amqp-transport/releases/tag/2.2.0).

**Comment by behrad** [comment]
so busy these days @nfantone 
What about I test the merged release, and let you know if any issues?

**Comment by behrad** [comment]
👍 thank you man

**Comment by behrad** [comment]
I tested 2.2.0 @nfantone and it looks great, however I've two main concerns:

1. Seneca client'a act is timed out when consumer is not running (the message will persist and be consumed by seneca listener later). In this case, can we increase act timeout to hours? minutes? to have a complete REQ/REP model? 
Related to the above, let me ask a general Senecajs question:
Can seneca support a non req/rep model? like workers or pub/sub, ...? I mean a case where act is not looking for a reply callback.

2. I benchmarked a Seneca mesh act as around 20ms in on the loopback address.
and Seneca amqp is around 45ms. Numbers look poor to me. Am i missing something?

**Comment by nfantone** [comment]
@behrad For point number one, please take a look [at this issue](https://github.com/senecajs/seneca-amqp-transport/issues/27).

Regarding your second point, I'm not familiar with seneca-mesh but, from what I saw, it's using HTTP as its default transport. Running HTTP on local LAN would beat queuing messages in an AMQP broker any day. Plus, persistence messages and queues with confirms are [particularly slow in RabbitMQ](https://stackoverflow.com/questions/20516450/ridiculously-slow-simultaneous-publish-consume-rate-with-rabbitmq) (see [this](https://groups.google.com/forum/#!topic/rabbitmq-users/BmhWLiAkm4E) also).
