### ISSUE TITLE
question: how to handle async processing

### ISSUE THREAD

**Issue by calvinwiebe** [senecajs/seneca-amqp-transport#99]
I want my message to be re-queued if my microservice dies while asynchronously processing the message. My consumer service's `add` function of seneca is doing some asynchronous processing. Something like this (typescript):

```typescript
seneca()
    .use('seneca-amqp-transport')
    .add('cmd:indexLog', (msg, cb: Function) => {
        return Promise.resolve()
            .then(() =>
                doSomethingAsynchronous()
                .then(
                    () => cb(null, { ok: true, when: Date.now() }),
                    (err: Error) => cb(err)
                )
            );
    })
    .listen({
        type: 'amqp',
        pin: 'cmd:indexLog',
        url: config.rabbit.connectionString
    });
```

The problem is, if somewhere inside `doSomethingAsynchronous` encounters an error and my microservice dies, it seems like the message is still `ack`ed. Therefore on restart of my microservice, the message I just received is lost. It looks like [this](https://github.com/senecajs/seneca-amqp-transport/blob/develop/lib/listener/consumer.js#L38-L39) bit expects the processing of the message to be synchronous? Am I going about this the wrong way? Any info would be greatly appreciated. Thanks!

**Comment by nfantone** [comment]
Hi, @calvinwiebe! First of all, +1 for the Calvin avatar. Hat tip.

The problem here is that, actually, you are misusing the Seneca reply callback. It's not terribly clear from the docs, but every error you send through or reply from an action is `fatal$` by default. That means that if you _do not pass`null` as the first argument_ of the the callback, your Seneca application **will terminate**. The `err` [argument](http://senecajs.org/api/old.html#params-3) is meant to signal an (possibly unrecoverable) error within the microservice action pipeline and **not a handling error** (like the one your example seems to be showing). You can override this, by setting `fatal$: false` [when calling your action](https://github.com/senecajs/seneca/issues/356#issuecomment-190324490).

Typically, what you'd want to do is to use some kind of boolean flag or status to represent your failure. Since you are already using an `ok` attribute, you can leverage its meaning and go with something like:

```js
    seneca()
    .add('cmd:indexLog', (msg, cb) => {
        return Promise.resolve()
            .then(() =>
                doSomethingAsynchronous()
                .then(() => cb(null, { ok: true, when: Date.now() }))
                .catch((err) => isErrorFatal(err) ? cb(err) : cb(null, { ok: false, reason: err.message }));
            );
    });
```

**Comment by calvinwiebe** [comment]
Hey, @nfantone. Thanks very much for the quick response. I'm also glad you enjoy the avatar. ;)

So, I get what you are saying about the Seneca callback. If I leave the default `fatal$: true`, and I do `cb(err)`, Seneca is going to kill my process. Conversely, doing `cb(null, someErrorObj)` will not kill my process, but send a not fatal message back over the queue. 

However, I think I am mentioning a different issue. Let's take the `cb(err)` example. Let's say some error occurs, and I _do_ deem it fatal, and I call `cb(err)`. My microservice is terminated by Seneca while I was processing the message (which I want). What I would want next is for my microservice to be started anew, and receive the same message from rabbitmq again so I could attempt to re-process it. Since the first process attempt never completed. However [this](https://github.com/senecajs/seneca-amqp-transport/blob/develop/lib/listener/consumer.js#L39) line will have already been called, which tells rabbitmq to forget about the message. 

Example, say I have this code:

```typescript
// put console.log in seneca-amqp-transport#consumer.js
try {
    handleMessage(content, curry(createReplyWith)(message));
    console.log('ACKING MESSAGE!');
    ch.ack(message);
  } catch (err) {
    // Failure to handle the message will result in it
    // being rejected (possibly sent to dead letter)
    ch.nack(message, false, false);
  }

// my application code
function doSomethingAsynchronous() {
    console.log('STARTING PROCESSING');
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('RECEIVED PROCESSING ERROR, DYING');
            reject(new Error('boom'));
        }, 2000);
    });
}

seneca()
    .use('seneca-amqp-transport')
    .add('cmd:indexLog', (msg, cb: Function) => {
        return Promise.resolve()
            .then(() =>
                doSomethingAsynchronous()
                .then(
                    () => cb(null, { ok: true, when: Date.now() }),
                    (err: Error) => cb(err)
                )
            );
    })
    .listen({
        type: 'amqp',
        pin: 'cmd:indexLog',
        url: config.rabbit.connectionString
    });
```

This logs the following:
```
ACKING MESSAGE!
STARTING PROCESSING
RECEIVED PROCESSING ERROR, DYING
{"notice":"seneca: Action cmd:indexLog failed: boom.","code":"act_execute" ...
SENECA TERMINATED at 2017-07-18T18:10:50.203Z. See above for error report
```
i.e. the `ACKING MESSAGE!` is the first bit of code to be executed, so we will always `ack` the message even if the processing of the message fails. (In fact I even tried to `throw` synchronously inside my `add` callback function, and `ACKING MESSAGE!` was still output)

Whereas, in [this](https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html) example code given by rabbitmq under **Message acknowledgment** they have the `ch.ack(msg)` inside the `setTimeout()` so that _Using this code we can be sure that even if you kill a worker using CTRL+C while it was processing a message, nothing will be lost._

That tutorial I mentioned above is a WorkQueue tutorial, and I realize that is on the roadmap. But, it seems to me that if `seneca-ampq-transport` is using `ch.ack(msg)`, it should wait until the processing of the task is complete before `ack`ing, no? Or am I still misinterpreting some intent here?

**Comment by nfantone** [comment]
@calvinwiebe The thing is, Seneca (and, consequently, this plugin) works in a sync RPC fashion: you send a message through your transport and a reply is expected sometime in the near future. Your scenario, as you pointed out, would be closer to a work queue topology where you delegate the duty of fulfilling some task to another service(s) and you don't really care _when_ it will be completed. It may fail any number of times, retry it, etc.

In the context of this transport, the acknowledgment of an AMQP message bears the meaning: "I have properly received this message and will now handle it". It's not (currently) tied to the success or failure of the actual handling. And it doesn't need to be.

> What I would want next is for my microservice to be started anew, and receive the same message from rabbitmq again so I could attempt to re-process it.

If you are going to implement a Seneca application, you need to actually avoid tying your routing or handling to the inner workings of a specific transport. Forget about queues and rabbits. In this schema, it is commonly the sender's responsibility to retry the operation. Most probably, it timed out or it received a non-ok response. EIther way, it becomes aware of the failure of the action it fired.

If this process doesn't suit your needs, I'd suggest staying off Seneca and implementing something either with plain `amqplib` or some other microservice oriented approach that doesn't abstract its transport so much. I'd argue that it'd actually be _easier_ if you don't plan on mixing or replacing transports (which is Seneca's bread and butter, really).

Having said all of that ☝️ , I am on board with you (and many others who have requested something similar) in this boat: sometimes you _don't need to wait for an answer_ or you don't care _when that answer arrives_. It'd nice if a client could do something like `.act({ do: 'something', async$: true }, cb);` and just forget about it - or wait for a response without timeoutting.

**Comment by calvinwiebe** [comment]
That is a great explanation. The `async$: true` parameter is exactly what I was thinking would be handy. However, I more fully understand the intent of a Seneca application after this discussion, and realize this type of parameter to `act` would slightly contradict Seneca's intent. Thanks again for the quick and helpful responses. 👍
